### ISSUE TITLE
Termina el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-marta-prieto#1]
Buen trabajo @marta-prieto  !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: un div o article que la englobe (mira el error que tienes en consola) y una imagen para mostrar el Pokemon
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser h3 sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [ ] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [ ] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [ ] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by marta-prieto** [comment]
Ya está todos los issues aplicados, y la página publicada en Github Pages.
Gracias!

**Comment by marta-prieto** [comment]
Lo único Carlos, no entiendo por qué si al lanzar desde code la página se ve con las tarjetas colocadas como en el diseño, y al haber publicado la web en giithub pages se descoloca. Quizás no haya publicado correctamente? Gracias.

**Comment by oneeyedman** [comment]
Te faltan algunas cosas que te he dejado sin marcar:

- [ ] Usa el id de cada pokemon para el key de react cuando mapeas y creas un listado de componentes
- [ ] Usa propTypes para comprobar el tipo de dato de las props
